include( 'shared.lua' )
include( 'Menus/cl_old_menu.lua' )
include( 'Menus/cl_new_menu.lua' )
include( 'Class/class_cl.lua' )
include( 'HitMarker/cl_hitdamagenumbers.lua' )
include( 'Props/cl_props.lua' )
include( 'Hands/cl_hands.lua' )
// Start of Scoreboard
include( "Scoreboard/admin_buttons.lua" )
include( "Scoreboard/cl_tooltips.lua" )
include( "Scoreboard/player_frame.lua" )
include( "Scoreboard/player_infocard.lua" )
include( "Scoreboard/player_row.lua" )
include( "Scoreboard/scoreboard.lua" )
include( "Scoreboard/vote_button.lua" )
include( "Scoreboard/the_scoreboard.lua" )
// End of Scoreboard
include( "Hud/cl_HUD.lua" )
include( "Hud/cl_Fonts.lua" )
include( 'UsMs/cl_msg.lua' )
include( 'FF/cl_friendlyfire.lua' )
include( 'Freeze/cl_freeze.lua' )
include( "Teams/cl_teams.lua"  )
include( 'Goal/cl_goal.lua' )
include( 'PlayerSpawns/cl_spawns.lua' )
include( 'LeaderBoards/cl_lb.lua' )